apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: real-secret-vol
            mountPath: /etc/config/myotherfile.txt
            subPath: myfile.yaml
      volumes:
        - name: real-secret-vol
          secret:
            secretName: real-secret

