apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mysecret-vol
            mountPath: /etc/stuff
          - name: real-secret-vol
            mountPath: /etc/config
      volumes:
        - name: mysecret-vol
          secret:
            secretName: mysecret
        - name: real-secret-vol
          secret:
            secretName: real-secret