apiVersion: v1
data:
  myfile.yaml: CnByZXR0eV9sb2c6IHRydWUKCiNsaXN0ZW46IHVuaXg6Ly8vdG1wL3BsdWdpbi5zb2NrCmxpc3RlbjogdGNwOi8vOjgwMDAKCnBpZF9maWxlOiAvdG1wL3BsdWdpbi5waWQKbG9ja19maWxlOiAvdG1wL3BsdWdpbi5sb2NrCgpuYW1lOiBwbHVnaW4tdmF1bHQKCndlYmhvb2s6CiAgcG9ydDogIjQ0NCIKICB0bHNDcnRGaWxlOiAiZGV2LWxhYi90bHMuY3J0IgogIHRsc0tleUZpbGU6ICJkZXYtbGFiL3Rscy5rZXkiCgp2YXVsdDoKICAjYWRkcmVzczogaHR0cDovL3ZhdWx0LXVpLnhkZS12YXVsdC5zdmM6ODIwMAogICMga3ViZWN0bCAtbiB4ZGUtdmF1bHQgcG9ydC1mb3J3YXJkIHNlcnZpY2UvdmF1bHQtdWkgODg4ODo4MjAwCiAgIyAgYWRkcmVzczogaHR0cDovL2xvY2FsaG9zdDo4ODg4CiAgIyAgdG9rZW46IHJvb3QKICAjICBwYXRoOiBzZWNyZXQKICBhZGRyZXNzOiBodHRwOi8vdmF1bHQtdWkudmF1bHQuc3ZjOjgyMDAKICB0b2tlbjogaHZzLkNBRVNJTU1RQXlGMEZJdE1rbHQ4WGJ6NFo2Q1pDSnBtOEJwZF85ZG0yOTU5OVMwa0doNEtIR2gyY3k1RmJVaERZVUkxTUV0WGFIVjNTRFZrVkVSbGQwNTNVSGMKICBwYXRoOiBzYXA=
  myproperties.properties: dG90bz10aXRpCg==
kind: Secret
metadata:
  name: real-secret
